// <auto-generated />
namespace TasteFoodIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_slider_class_and_AddColumns_AdminClass_NameSurname_and_ImageUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_slider_class_and_AddColumns_AdminClass_NameSurname_and_ImageUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "202403121947198_add_slider_class_and_AddColumns_AdminClass_NameSurname_and_ImageUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
