// <auto-generated />
namespace TasteFoodIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_MailClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_MailClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202403061022317_add_MailClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
