// <auto-generated />
namespace TasteFoodIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_class_mailbox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_class_mailbox));
        
        string IMigrationMetadata.Id
        {
            get { return "202403111158206_add_class_mailbox"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
